import { useState, useEffect } from "react";
import { useAccount, useWriteContract, useSwitchChain, useWalletClient } from "wagmi";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Sparkles, Zap, RefreshCw, ChevronUp } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useAllMarkets } from "@/hooks/useMarkets";
import { URIM_QUANTUM_MARKET_ADDRESS, URIM_MARKET_ADDRESS, USDC_ADDRESS } from "@/constants/contracts";
import UrimQuantumMarketABI from "@/contracts/UrimQuantumMarket.json";
import UrimMarketABI from "@/contracts/UrimMarket.json";
import ERC20ABI from "@/contracts/ERC20.json";
import { parseUnits } from "viem";
import PythPriceTicker from "@/components/PythPriceTicker";
import { EvmPriceServiceConnection } from "@pythnetwork/pyth-evm-js";
import { initializeWithProvider, isInitialized, getUnifiedBalances } from "@/lib/nexus";
import { BridgeAndExecuteButton } from '@avail-project/nexus-widgets';
import { supabase } from "@/integrations/supabase/client";
import { optimismSepolia, baseSepolia } from 'wagmi/chains';
import Bridge from '@/components/BridgeButton';
import { useNotification } from "@blockscout/app-sdk";

import LiveQuantumMarkets from "@/components/LiveQuantumMarkets";

const ETH_USD_PRICE_FEED = "0xff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace";
const connection = new EvmPriceServiceConnection("https://hermes.pyth.network");

type ProcessedBalance = {
  symbol: string;
  icon: string;
  totalBalance: string;
  chains: {
    chainName: string;
    balance: string;
    icon: string;
  }[];
};

const Index = () => {
  const { switchChain } = useSwitchChain();
  const { address, isConnected, chain } = useAccount();
  const { data: walletClient } = useWalletClient();
  const { toast } = useToast();
  const { writeContractAsync } = useWriteContract();
  const { openTxToast } = useNotification();
  
  const [question, setQuestion] = useState("");
  const [generating, setGenerating] = useState(false);
  
  // Active markets generated by the user
  const [activeMarkets, setActiveMarkets] = useState<Array<{
    id: string;
    question: string;
    outcomes: Array<{
      description: string;
      probability: string;
    }>;
    betAmounts: string[];
  }>>([]);
  
  const [nexusInitialized, setNexusInitialized] = useState(false);
  const [processedBalances, setProcessedBalances] = useState<ProcessedBalance[]>([]);
  const [initializingNexus, setInitializingNexus] = useState(false);
  const [balanceLoading, setBalanceLoading] = useState(false);
  const [balanceError, setBalanceError] = useState<string | null>(null);
  const [expandedTokens, setExpandedTokens] = useState<Set<string>>(new Set());
  const [unifiedBalance, setUnifiedBalance] = useState<string>("0.0000");
  
  const [currentPrice, setCurrentPrice] = useState<number>(0);
  const [pythMarkets, setPythMarkets] = useState<Array<{
    id: string;
    question: string;
    threshold: number;
    marketId: bigint | null;
    selectedOutcome: 'yes' | 'no' | null;
    betAmount: string;
    creating: boolean;
    betting: boolean;
    bridging: boolean;
  }>>([]);

  const isOnOptimismSepolia = chain?.id === optimismSepolia.id;
  const { quantumMarketIds, everythingMarketIds } = useAllMarkets();

  const fetchBalances = async () => {
    if (!isInitialized()) {
      return;
    }
    
    setBalanceLoading(true);
    setBalanceError(null);
    
    try {
      const rawBalances = await getUnifiedBalances();
      console.log('Raw Data from Nexus:', rawBalances);
      
      const processed: ProcessedBalance[] = rawBalances
        .filter((token: any) => parseFloat(token.balance) > 0)
        .map((token: any) => {
          const chainsWithBalance = token.breakdown
            .filter((chain: any) => parseFloat(chain.balance) > 0)
            .map((chain: any) => ({
              chainName: chain.chain.name || 'Unknown Chain',
              balance: chain.balance,
              icon: chain.chain.logo,
            }));

          return {
            symbol: token.symbol,
            icon: token.icon,
            totalBalance: token.balance,
            chains: chainsWithBalance,
          };
        });

      console.log('Processed Data for UI:', processed);
      setProcessedBalances(processed);
      
      const total = rawBalances.reduce((sum: number, token: any) => 
        sum + parseFloat(token.balance || "0"), 0
      );
      setUnifiedBalance(total.toFixed(4));
    } catch (e: any) {
      console.error("Failed to fetch balances:", e);
      setBalanceError(e.message || "Failed to fetch balance");
      setProcessedBalances([]);
      setUnifiedBalance("0.0000");
    } finally {
      setBalanceLoading(false);
    }
  };

  useEffect(() => {
    const autoInitNexus = async () => {
      if (!isConnected || !walletClient) return;
      
      if (isInitialized()) {
        setNexusInitialized(true);
        await fetchBalances();
        return;
      }
      
      try {
        setInitializingNexus(true);
        await initializeWithProvider(walletClient);
        setNexusInitialized(true);
        await fetchBalances();
        console.log("✅ Nexus auto-initialized");
      } catch (error) {
        console.error("Auto-init failed:", error);
      } finally {
        setInitializingNexus(false);
      }
    };
    
    autoInitNexus();
  }, [isConnected, walletClient]);

  useEffect(() => {
    const fetchPrice = async () => {
      try {
        const priceFeeds = await connection.getLatestPriceFeeds([ETH_USD_PRICE_FEED]);
        if (priceFeeds && priceFeeds.length > 0) {
          const priceFeed = priceFeeds[0];
          const price = priceFeed.getPriceUnchecked();
          const formattedPrice = Number(price.price) * Math.pow(10, price.expo);
          setCurrentPrice(formattedPrice);

          if (pythMarkets.length === 0 && formattedPrice > 0) {
            const roundedPrice = Math.round(formattedPrice);
            const aboveThreshold = roundedPrice + Math.round(formattedPrice * 0.02);
            const belowThreshold = roundedPrice - Math.round(formattedPrice * 0.02);

            setPythMarkets([
              {
                id: 'pyth-above',
                question: `Will ETH close above $${aboveThreshold} tomorrow?`,
                threshold: aboveThreshold,
                marketId: null,
                selectedOutcome: null,
                betAmount: '',
                creating: false,
                betting: false,
                bridging: false,
              },
              {
                id: 'pyth-below',
                question: `Will ETH close below $${belowThreshold} tomorrow?`,
                threshold: belowThreshold,
                marketId: null,
                selectedOutcome: null,
                betAmount: '',
                creating: false,
                betting: false,
                bridging: false,
              }
            ]);
          }
        }
      } catch (error) {
        console.error("Error fetching price:", error);
      }
    };

    fetchPrice();
    const interval = setInterval(fetchPrice, 10000);
    return () => clearInterval(interval);
  }, [pythMarkets.length]);

  const handleInitNexus = async () => {
    if (!walletClient) {
      toast({ title: "Connect wallet first", variant: "destructive" });
      return;
    }

    setInitializingNexus(true);
    setBalanceError(null);
    try {
      await initializeWithProvider(walletClient);
      setNexusInitialized(true);
      await fetchBalances();
      toast({ title: "🌉 Nexus Initialized", description: "Avail bridge ready!" });
    } catch (error: any) {
      console.error("Nexus init failed:", error);
      setBalanceError(error.message || "Initialization failed");
      toast({ title: "Initialization failed", description: error.message, variant: "destructive" });
    } finally {
      setInitializingNexus(false);
    }
  };

  const toggleTokenExpansion = (token: string) => {
    const newExpanded = new Set(expandedTokens);
    if (newExpanded.has(token)) {
      newExpanded.delete(token);
    } else {
      newExpanded.add(token);
    }
    setExpandedTokens(newExpanded);
  };

  const handleGenerate = async () => {
    if (!question.trim()) {
      toast({ title: "Enter a question", variant: "destructive" });
      return;
    }

    setGenerating(true);

    try {
      toast({ title: "🧠 Generating outcomes...", description: "AI is analyzing your question" });

      const { data, error } = await supabase.functions.invoke('generate-scenarios', {
        body: { question: question.trim() }
      });

      if (error) throw error;

      const scenarioDescriptions = data?.scenarios?.map((s: any) => s.description) || [
        "Yes, it will happen",
        "No, it will not happen"
      ];
      
      const finalScenarios = scenarioDescriptions.length >= 2 
        ? scenarioDescriptions.slice(0, 2) 
        : ["Yes, it will happen", "No, it will not happen"];
      
      // Generate random probabilities that add up to 100%
      const prob1 = Math.floor(Math.random() * 30) + 40; // 40-70%
      const prob2 = 100 - prob1;

      const newMarket = {
        id: Date.now().toString(),
        question: question.trim(),
        outcomes: [
          { description: finalScenarios[0], probability: `${prob1}%` },
          { description: finalScenarios[1], probability: `${prob2}%` }
        ],
        betAmounts: ["", ""]
      };

      setActiveMarkets(prev => [newMarket, ...prev]);
      setQuestion("");
      
      toast({ 
        title: "✨ Market Generated!", 
        description: "Your quantum market is ready for betting"
      });

    } catch (error: any) {
      console.error("Market generation error:", error);
      toast({
        title: "❌ Generation failed",
        description: error.message || "Please try again",
        variant: "destructive"
      });
    } finally {
      setGenerating(false);
    }
  };

  const createPythMarket = async (marketIndex: number) => {
    if (!address) {
      toast({ title: "Connect Wallet", description: "Please connect your wallet first.", variant: "destructive" });
      return;
    }

    const market = pythMarkets[marketIndex];
    if (!market) return;

    setPythMarkets(prev => prev.map((m, i) => i === marketIndex ? { ...m, creating: true } : m));

    try {
      toast({ title: "Creating Pyth Market...", description: "Confirm transaction in wallet" });

      const duration = BigInt(24 * 60 * 60);
      const priceFeedId = ETH_USD_PRICE_FEED as `0x${string}`;
      const targetPrice = BigInt(Math.round(market.threshold * 1e8));

      const hash = await writeContractAsync({
        address: URIM_QUANTUM_MARKET_ADDRESS as `0x${string}`,
        abi: UrimQuantumMarketABI.abi as any,
        functionName: "createMarket",
        args: [market.question, "Yes", "No", duration, priceFeedId, targetPrice],
        gas: BigInt(3_000_000),
      } as any);

      openTxToast("84532", hash);

      setTimeout(() => {
        if (quantumMarketIds && quantumMarketIds.length > 0) {
          const newMarketId = quantumMarketIds[quantumMarketIds.length - 1];
          setPythMarkets(prev => prev.map((m, i) => 
            i === marketIndex ? { ...m, marketId: newMarketId, creating: false } : m
          ));
        }
      }, 2000);
    } catch (error: any) {
      console.error("Error creating Pyth market:", error);
      toast({
        title: "Transaction failed",
        description: error.message || "Please try again",
        variant: "destructive",
      });
      setPythMarkets(prev => prev.map((m, i) => i === marketIndex ? { ...m, creating: false } : m));
    }
  };

  const handlePythPlaceBet = async (marketIndex: number) => {
    const market = pythMarkets[marketIndex];
    if (!address || !market.marketId || !market.selectedOutcome || !market.betAmount) {
      toast({ title: "Missing Information", description: "Please select an outcome and enter bet amount.", variant: "destructive" });
      return;
    }

    setPythMarkets(prev => prev.map((m, i) => i === marketIndex ? { ...m, betting: true } : m));

    try {
      const amountWei = parseUnits(market.betAmount, 6);
      const outcomeIndex = market.selectedOutcome === 'yes' ? 0 : 1;

      await writeContractAsync({
        address: USDC_ADDRESS as `0x${string}`,
        abi: ERC20ABI.abi as any,
        functionName: "approve",
        args: [URIM_QUANTUM_MARKET_ADDRESS, amountWei],
      } as any);

      const hash = await writeContractAsync({
        address: URIM_QUANTUM_MARKET_ADDRESS as `0x${string}`,
        abi: UrimQuantumMarketABI.abi as any,
        functionName: "buyScenarioShares",
        args: [market.marketId, BigInt(outcomeIndex), amountWei],
        gas: BigInt(3_000_000),
      } as any);

      openTxToast("84532", hash);

      setPythMarkets(prev => prev.map((m, i) => i === marketIndex ? { ...m, betAmount: '', betting: false } : m));
    } catch (error: any) {
      console.error("Error placing bet:", error);
      toast({
        title: "Transaction failed",
        description: error.message || "Please try again",
        variant: "destructive",
      });
      setPythMarkets(prev => prev.map((m, i) => i === marketIndex ? { ...m, betting: false } : m));
    }
  };

  const handlePythBridgeAndBet = async (marketIndex: number) => {
    const market = pythMarkets[marketIndex];
    if (!address || !market.marketId || !market.selectedOutcome || !market.betAmount) {
      toast({ title: "Missing Information", description: "Please select an outcome and enter bet amount.", variant: "destructive" });
      return;
    }

    setPythMarkets(prev => prev.map((m, i) => i === marketIndex ? { ...m, bridging: true } : m));

    try {
      toast({ title: "🌉 Bridging with Avail...", description: "This may take a moment" });
      
      await handlePythPlaceBet(marketIndex);
    } catch (error: any) {
      console.error("Bridge failed:", error);
      toast({
        title: "Bridge failed",
        description: "You can still place a bet directly.",
        variant: "destructive",
      });
      setPythMarkets(prev => prev.map((m, i) => i === marketIndex ? { ...m, bridging: false } : m));
    }
  };

  const handlePlaceBet = (marketIndex: number, outcomeIndex: number) => {
    const market = activeMarkets[marketIndex];
    const amount = market.betAmounts[outcomeIndex];
    
    if (!amount || parseFloat(amount) <= 0) {
      toast({ title: "Enter bet amount", variant: "destructive" });
      return;
    }

    // Placeholder - no blockchain transaction
    console.log("Bet placed (placeholder):", {
      market: market.question,
      outcome: market.outcomes[outcomeIndex].description,
      amount: amount
    });

    toast({ 
      title: "🎲 Bet Placed (Demo Mode)", 
      description: `${amount} USDC on: ${market.outcomes[outcomeIndex].description.substring(0, 40)}...`
    });

    // Clear the bet amount
    setActiveMarkets(prev => prev.map((m, i) => {
      if (i === marketIndex) {
        const newAmounts = [...m.betAmounts];
        newAmounts[outcomeIndex] = "";
        return { ...m, betAmounts: newAmounts };
      }
      return m;
    }));
  };

  const updateBetAmount = (marketIndex: number, outcomeIndex: number, value: string) => {
    setActiveMarkets(prev => prev.map((m, i) => {
      if (i === marketIndex) {
        const newAmounts = [...m.betAmounts];
        newAmounts[outcomeIndex] = value;
        return { ...m, betAmounts: newAmounts };
      }
      return m;
    }));
  };

  return (
    <div className="min-h-screen w-full bg-background relative">
      <Navigation />
      
      {/* Quantum Market Generator Section - Top of Page */}
      <section className="max-w-4xl mx-auto px-6 pt-20 md:pt-28 lg:pt-32 pb-16">
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/20 border border-primary/30 mb-4">
            <Sparkles className="w-4 h-4 text-primary" />
            <span className="text-xs font-bold uppercase tracking-wider">🧠 AI-Powered</span>
          </div>
          <h2 className="text-4xl font-bold mb-3">✦ Quantum Market Generator</h2>
          <p className="text-muted-foreground text-lg">Create custom prediction markets with AI-generated outcomes.</p>
        </div>

        <div className="glass-card p-8 mb-8">
          <div className="space-y-4">
            <div>
              <label className="text-sm font-semibold mb-2 block">Your Question</label>
              <Input
                type="text"
                placeholder="Will ETH close above $4000 tomorrow?"
                value={question}
                onChange={(e) => setQuestion(e.target.value)}
                className="text-lg font-semibold"
                style={{
                  background: '#171218',
                  color: '#FFFFFF',
                  border: '1px solid #5B3FB8',
                }}
                onFocus={(e) => e.target.style.borderColor = '#8B6DFF'}
                onBlur={(e) => e.target.style.borderColor = '#5B3FB8'}
              />
            </div>

            <Button
              onClick={handleGenerate}
              disabled={generating || !question.trim()}
              className="w-full bg-gradient-to-r from-primary to-primary-glow hover:shadow-[0_0_40px_rgba(139,109,255,0.4)] transition-all duration-300"
              size="lg"
            >
              {generating ? (
                <>
                  <RefreshCw className="w-5 h-5 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Zap className="w-5 h-5 mr-2" />
                  Generate Quantum Market
                </>
              )}
            </Button>
          </div>
        </div>
      </section>

      {/* Active Quantum Markets - User-generated markets from Quantum Market Generator */}
      <section className="max-w-6xl mx-auto px-6 pb-16">
        <h2 className="text-3xl font-bold mb-8 text-center bg-gradient-to-r from-primary via-purple-400 to-primary bg-clip-text text-transparent">
          ✨ Active Quantum Markets
        </h2>
        
        {activeMarkets.length === 0 ? (
          <div className="text-center py-12 text-muted-foreground">
            <p className="text-lg">No markets created yet. Generate your first quantum market above! ⬆️</p>
          </div>
        ) : (
          <div className="space-y-8">
            {activeMarkets.map((market, marketIdx) => (
              <div key={market.id} className="glass-card p-6">
                <h3 className="text-xl font-semibold mb-6 text-foreground/90">
                  {market.question}
                </h3>
                
                <div className="grid md:grid-cols-2 gap-6">
                  {market.outcomes.map((outcome, outcomeIdx) => (
                    <div
                      key={outcomeIdx}
                      className="relative group/card"
                    >
                      <div className="absolute -inset-0.5 bg-gradient-to-br from-primary/40 to-purple-500/40 rounded-xl blur opacity-0 group-hover/card:opacity-100 transition-all duration-300" />
                      
                      <div className="relative bg-background/80 border border-primary/20 rounded-xl p-5 space-y-4">
                        <div className="space-y-2">
                          <div className="flex items-start justify-between gap-2">
                            <p className="text-sm font-medium text-foreground/80 leading-relaxed flex-1">
                              {outcome.description}
                            </p>
                            <span className="px-3 py-1 bg-primary/10 text-primary text-xs font-semibold rounded-full shrink-0">
                              {outcome.probability}
                            </span>
                          </div>
                        </div>
                        
                        <div className="space-y-3">
                          <Input
                            type="number"
                            placeholder="Amount (USDC)"
                            value={market.betAmounts[outcomeIdx]}
                            onChange={(e) => updateBetAmount(marketIdx, outcomeIdx, e.target.value)}
                            className="h-10 bg-background/50 border-primary/20 focus:border-primary/50"
                          />
                          
                          <Button
                            onClick={() => handlePlaceBet(marketIdx, outcomeIdx)}
                            disabled={!market.betAmounts[outcomeIdx] || parseFloat(market.betAmounts[outcomeIdx]) <= 0}
                            className="w-full bg-primary/90 hover:bg-primary text-primary-foreground shadow-[0_0_20px_rgba(124,58,237,0.2)] hover:shadow-[0_0_30px_rgba(124,58,237,0.4)] transition-all"
                          >
                            Bet
                          </Button>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}
      </section>

      <section className="max-w-4xl mx-auto px-6 pb-24">
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/20 border border-primary/30 mb-4">
            <Sparkles className="w-4 h-4 text-primary" />
            <span className="text-xs font-bold uppercase tracking-wider">Oracle-Powered</span>
          </div>
          <h2 className="text-4xl font-bold mb-3">✦ Quantum Pyth</h2>
          <p className="text-muted-foreground text-lg">AI-generated futures from live Pyth price feeds.</p>
        </div>

        <div className="grid md:grid-cols-2 gap-6">
          {pythMarkets.map((market, marketIndex) => (
            <div key={market.id} className="glass-card p-6">
              <div className="text-lg font-semibold mb-4">{market.question}</div>
              
              {!market.marketId ? (
                <Button 
                  onClick={() => createPythMarket(marketIndex)}
                  disabled={market.creating}
                  className="w-full bg-gradient-to-r from-primary to-primary-glow"
                >
                  {market.creating ? "Creating Market..." : "Create Market"}
                </Button>
              ) : (
                <div className="space-y-4">
                  <div className="grid grid-cols-2 gap-3">
                    <Button 
                      variant="outline" 
                      className={`border-2 transition-all ${
                        market.selectedOutcome === 'yes'
                          ? 'border-green-500 bg-green-500/20' 
                          : 'border-green-500/50 hover:bg-green-500/10'
                      }`}
                      onClick={() => setPythMarkets(prev => prev.map((m, i) => 
                        i === marketIndex ? { ...m, selectedOutcome: 'yes' } : m
                      ))}
                    >
                      Yes
                    </Button>
                    <Button 
                      variant="outline"
                      className={`border-2 transition-all ${
                        market.selectedOutcome === 'no'
                          ? 'border-red-500 bg-red-500/20' 
                          : 'border-red-500/50 hover:bg-red-500/10'
                      }`}
                      onClick={() => setPythMarkets(prev => prev.map((m, i) => 
                        i === marketIndex ? { ...m, selectedOutcome: 'no' } : m
                      ))}
                    >
                      No
                    </Button>
                  </div>

                  {market.selectedOutcome && (
                    <div className="space-y-3 animate-fade-in">
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-semibold">💰</span>
                        <Input 
                          type="number" 
                          placeholder="0.1" 
                          value={market.betAmount}
                          onChange={(e) => setPythMarkets(prev => prev.map((m, i) => 
                            i === marketIndex ? { ...m, betAmount: e.target.value } : m
                          ))}
                          className="flex-1 font-semibold"
                          style={{
                            background: '#171218',
                            color: '#FFFFFF',
                            border: '1px solid #5B3FB8',
                          }}
                          onFocus={(e) => e.target.style.borderColor = '#8B6DFF'}
                          onBlur={(e) => e.target.style.borderColor = '#5B3FB8'}
                        />
                        <span className="text-sm font-bold" style={{ color: '#D9CCFF', opacity: 0.9 }}>USDC</span>
                      </div>

                      <div className="space-y-2">
                        <Button 
                          onClick={() => handlePythPlaceBet(marketIndex)}
                          disabled={market.betting || !market.betAmount || parseFloat(market.betAmount) <= 0}
                          className="w-full bg-gradient-to-r from-primary to-primary-glow"
                        >
                          {market.betting ? "Placing..." : "Place Bet"}
                        </Button>

                        <Button 
                          onClick={() => handlePythBridgeAndBet(marketIndex)}
                          disabled={market.bridging || market.betting || !market.betAmount || parseFloat(market.betAmount) <= 0}
                          variant="outline"
                          className="w-full rounded-full"
                          style={{
                            border: '1px solid #8B6DFF',
                            color: '#CDBBFF',
                          }}
                          onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(139,109,255,0.15)'}
                          onMouseLeave={(e) => e.currentTarget.style.background = 'transparent'}
                        >
                          {market.bridging ? "Bridging..." : "Bridge & Bet with Avail"}
                        </Button>
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      <section className="max-w-6xl mx-auto px-6 pb-16">
        <PythPriceTicker />
        <LiveQuantumMarkets />
      </section>

      <Footer />
    </div>
  );
};

export default Index;